FROM tensorflow/tensorflow:1.15.5

RUN apt-get -y update
RUN apt-get -y install python3 && python3 -m pip install --upgrade pip
RUN apt-get -y install graphviz
RUN pip install numpy matplotlib sklearn pydot pydotplus -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pandas bioservices tqdm -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install xgboost imblearn -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app


